language: python
install:
  - pip install tox
  - pip install coveralls
  - "if [[ $TOXENV == 'py34' ]]; then .travis/py34.sh; fi"
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=coverage27
  - TOXENV=coverage33
script:
  - tox
after_success:
  - coveralls
