language: python
python: 2.7
install:
  - pip install tox
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  # Travis no longer supports Python 3.1
  #  - TOX_ENV=py31
  - TOX_ENV=py32
  - TOX_ENV=py33
script:
  - tox -e $TOX_ENV
